services:
  postgres:
    image: postgres:latest
    container_name: saas-db
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-saas-db}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - saas-app-network
    restart: unless-stopped

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    ports:
#      - "9000:80"

volumes:
  postgres_data:
    driver: local

networks:
  saas-app-network:
    driver: bridge